echo  > myfile.txt && rm myfile.txt && echo "Youre watching; ANALOG HORROR on DRAGON TV" > myfile.txt & timeout 1m mpv https://adultswim-vodlive.cdn.turner.com/live/test-1/stream.m3u8 --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "DRAGON TV" > myfile.txt & mpv https://files.catbox.moe/wu470y.mp4 --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; TECH C0RN3R on DRAGON TV" > myfile.txt & mpv "https://odysee.com/@mattdoestech726:5/leopard-on-lion-mid-2012-mac-book-pro:8" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "DRAGON TV" > myfile.txt & mpv https://files.catbox.moe/wu470y.mp4 --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching;  ANIME on DRAGON TV" > myfile.txt & timeout 40m mpv "http://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/60f74ba51c82ac000776c669/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=1YNY&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&profileLimit=&profileFloor=&embedPartner=samsung-tvplus" --end=40 --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "DRAGON TV" > myfile.txt & mpv https://files.catbox.moe/wu470y.mp4 --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; TECH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ZackFreedman --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "DRAGON TV" > myfile.txt & mpv https://files.catbox.moe/wu470y.mp4 --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching;  ANIME on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.twitch.tv/everyday ANIME --screen=1 -sid=auto --slang=en 
# echo  > myfile.txt && rm myfile.txt && echo "Youre watching;  ANIME on DRAGON TV" > myfile.txt & timeout 40m mpv http://live.roomba.tv:80/69858725/35787922/1860109.ts --screen=1 -sid=auto --slang=en 
# echo  > myfile.txt && rm myfile.txt && echo "Youre watching;  ANIME on DRAGON TV" > myfile.txt & timeout 40m mpv http://live.roomba.tv:80/69858725/35787922/1860862.ts --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; ANALOG HORROR on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/channel/UCuoMasRkMhlj1VNVAOJdw5w/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; ANALOG HORROR on DRAGON TV" > myfile.txt & timeout 130m mpv https://www.youtube.com/c/Nexpo/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@XboxAhoy/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/channel/UCy0tKL1T7wFoYcxCe0xjN6Q/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/channel/UC1ydE9gDHTdvbNVIgEKIKzw/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/playlist?list=PLHmR7c8zbVZRLORCvg7Thz-2PG126KmDA --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; ANALOG HORROR on DRAGON TV" > myfile.txt & timeout 7m mpv https://files.catbox.moe/4qk5zv.mp4 --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/playlist?list=PLHmR7c8zbVZRLORCvg7Thz-2PG126KmDA --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; SPACE C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/channel/UC-9b7aDP6ZN0coj9-xFnrtw/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DJ TIME on DRAGON TV" > myfile.txt & timeout 40m mpv https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/dash/nonuk/dash_low/aks/bbc_radio_one.mpd --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@MattKC/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/c/BraxMe/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/user/channelnewsasia/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/c/ActionRetro/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@BBCNews/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@BBCReel/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@bbclondon/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@bbcearth/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@BBCArchive/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@OBFYT/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@johnnyharris/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 --sid=2
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/Vice/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/VICEAsia/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@CNAInsider/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/ColdFusion/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/user/ibx2cat/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/Coffeezilla/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; SPACE C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/DrBecky --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; TECH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ComputerClan/--ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; TECH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/channel/UCuoMasRkMhlj1VNVAOJdw5w/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; TECH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@idevicecentral/--ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; TECH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@lukemiani/--ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; TECH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@macaddress/--ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@Beta64/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/CubeComputerChannel/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@CraftComputing/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@CNET/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@Madlittlepixel/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ETAPRIME/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@DistroTube/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@JohnGlasscock/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@_JohnHammond/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@rossmanngroup/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LowSpecGamer/videos --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LinusTechTips/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@IGN/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@GamersNexus/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@EposVox/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@JeffGeerling/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LonSeidman/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@peterc408/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@TechDoctorUK/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ThinkFrugal/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@AntennaMan/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@clarkss12/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LGR/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LIRetroGaming/ --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
# echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DJ TIME on DRAGON TV" > myfile.txt & timeout 40m mpv https://music.youtube.com/playlist?list=PLfG9GoN29wAFb3A3RFflaC7li8wm9jyCh --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LastWeekTonight --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ricksteves --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; SPACE C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@whatdamath --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; SPACE C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/user/universetoday --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; SPACE C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@pbsspacetime --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; SPACE C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ElderFoxDocumentaries --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; SPACE C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@TheSpaceRaceYT --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; SPACE C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@MarsGuy --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; SPACE C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@AstroBackyard --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
echo  > myfile.txt && rm myfile.txt && echo "Youre watching; R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@mylifeingaming --ytdl-format="mp4[height<=?720][fps<=?30]+bestaudio/best" --screen=1 -sid=auto --slang=en 
