echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Creepypasta Content on DRAGON TV" > myfile.txt & timeout 1m mpv https://adultswim-vodlive.cdn.turner.com/live/test-1/stream.m3u8 -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "DRAGON TV" > myfile.txt & mpv https://files.catbox.moe/wu470y.mp4 -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; AUSTIN TV's TECH CORNOR on DRAGON TV" > myfile.txt & mpv https://player.odycdn.com/api/v4/streams/free/leopard-on-lion-mid-2012-mac-book-pro/8ae8e58514e38ce1d4aa2a0236264eda63e1ecca/371e02 -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "DRAGON TV" > myfile.txt & mpv https://files.catbox.moe/wu470y.mp4 -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; Anime on DRAGON TV" > myfile.txt & timeout 40m mpv "http://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/60f74ba51c82ac000776c669/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=1YNY&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&profileLimit=&profileFloor=&embedPartner=samsung-tvplus" --end=40 -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "DRAGON TV" > myfile.txt & mpv https://files.catbox.moe/wu470y.mp4 -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; AUSTIN TV's TECH CORNOR on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ZackFreedman $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "DRAGON TV" > myfile.txt & mpv https://files.catbox.moe/wu470y.mp4 -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; Anime on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.twitch.tv/everydayanime -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; Anime on DRAGON TV" > myfile.txt & timeout 40m mpv http://live.roomba.tv:80/69858725/35787922/1860109.ts -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; Anime on DRAGON TV" > myfile.txt & timeout 40m mpv http://live.roomba.tv:80/69858725/35787922/1860862.ts -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; AUSTIN TV's TECH CORNOR on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/channel/UCuoMasRkMhlj1VNVAOJdw5w/videos --shuffle $Q -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Creepypasta Content on DRAGON TV" > myfile.txt & timeout 130m mpv https://www.youtube.com/c/Nexpo/videos $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; SpicyOREO & VENOM's R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@XboxAhoy/videos $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; SpicyOREO & VENOM's R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/channel/UCy0tKL1T7wFoYcxCe0xjN6Q/videos $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; SpicyOREO & VENOM's R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/channel/UC1ydE9gDHTdvbNVIgEKIKzw/videos $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; SpicyOREO & VENOM's R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/playlist?list=PLHmR7c8zbVZRLORCvg7Thz-2PG126KmDA $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Creepypasta Content on DRAGON TV" > myfile.txt & timeout 7m mpv https://files.catbox.moe/4qk5zv.mp4 -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; SpicyOREO & VENOM's R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/playlist?list=PLHmR7c8zbVZRLORCvg7Thz-2PG126KmDA $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Space C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/channel/UC-9b7aDP6ZN0coj9-xFnrtw/videos $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; DJ VENOM's on DRAGON TV" > myfile.txt & timeout 40m mpv https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/dash/nonuk/dash_low/aks/bbc_radio_one.mpd -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@MattKC/videos $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/c/BraxMe/videos $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/user/channelnewsasia/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/c/ActionRetro/videos $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@BBCNews/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@BBCReel/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@bbclondon/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@bbcearth/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@BBCArchive/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@OBFYT/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@johnnyharris/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/Vice/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/VICEAsia/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@CNAInsider/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/ColdFusion/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/user/ibx2cat/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/Coffeezilla/ $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Space C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/DrBecky $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; AUSTIN TV's TECH CORNOR on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ComputerClan/ --shuffle $Q -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; AUSTIN TV's TECH CORNOR on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/channel/UCuoMasRkMhlj1VNVAOJdw5w/videos --shuffle $Q -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; AUSTIN TV's TECH CORNOR on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@idevicecentral/ --shuffle $Q -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; AUSTIN TV's TECH CORNOR on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@lukemiani/ --shuffle $Q -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; AUSTIN TV's TECH CORNOR on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@macaddress/ --shuffle $Q -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@Beta64/videos $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/CubeComputerChannel/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@CraftComputing/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@CNET/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@Madlittlepixel/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ETAPRIME/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@DistroTube/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@JohnGlasscock/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@_JohnHammond/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@rossmanngroup/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LowSpecGamer/videos $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LinusTechTips/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@IGN/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@GamersNexus/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@EposVox/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@JeffGeerling/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LonSeidman/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@peterc408/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@TechDoctorUK/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ThinkFrugal/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@AntennaMan/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's T3CH C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@clarkss12/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; SpicyOREO & VENOM's R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LGR/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; SpicyOREO & VENOM's R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LIRetroGaming/ $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; DJ VENOM's on DRAGON TV" > myfile.txt & timeout 40m mpv https://music.youtube.com/playlist?list=PLfG9GoN29wAFb3A3RFflaC7li8wm9jyCh $Q --shuffle player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@LastWeekTonight $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's DOC C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ricksteves $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Space C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@whatdamath $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Space C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/user/universetoday $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Space C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@pbsspacetime $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Space C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@ElderFoxDocumentaries $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Space C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@TheSpaceRaceYT $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Space C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@MarsGuy $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; VENOM's Space C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@AstroBackyard $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1
echo  > myfile.txt && rm myfile.txt && echo "You're watching; SpicyOREO & VENOM's R3TR0 C0RN3R on DRAGON TV" > myfile.txt & timeout 40m mpv https://www.youtube.com/@mylifeingaming $Q --shuffle -player-operation-mode=pseudo-gui --screen=1 --sid=1

