yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@AntennaMan > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@AstroBackyard > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@BBCArchive > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@BBCNews > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@BBCReel > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@Beta64/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@CNAInsider > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@CNET > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@ComputerClan > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@CraftComputing > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@DistroTube > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@ETAPRIME > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@ElderFoxDocumentaries > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@EposVox > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@GamersNexus > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@IGN > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@JeffGeerling > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@JohnGlasscock > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@LGR > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@LIRetroGaming > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@LastWeekTonight > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@LinusTechTips > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@LonSeidman > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@LowSpecGamer/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@Madlittlepixel > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@MarsGuy > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@MattKC/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@OBFYT > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@TechDoctorUK > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@TheSpaceRaceYT > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@ThinkFrugal > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@XboxAhoy/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@ZackFreedman > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@_JohnHammond > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@bbcearth > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@bbclondon > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@clarkss12 > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@idevicecentral/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@johnnyharris > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@lukemiani/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@macaddress/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@mylifeingaming > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@pbsspacetime > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@peterc408 > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@ricksteves > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@rossmanngroup > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/@whatdamath > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/Coffeezilla > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/ColdFusion > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/CubeComputerChannel > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/DrBecky > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/VICEAsia > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/Vice/ > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/c/ActionRetro/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/c/BraxMe/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/c/Nexpo/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/channel/UC-9b7aDP6ZN0coj9-xFnrtw/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/channel/UC1ydE9gDHTdvbNVIgEKIKzw/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/channel/UCuoMasRkMhlj1VNVAOJdw5w/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/channel/UCy0tKL1T7wFoYcxCe0xjN6Q/videos > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/playlist?list=PLHmR7c8zbVZRLORCvg7Thz-2PG126KmDA > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/user/channelnewsasia > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/user/ibx2cat > playlist2.m3u
yt-dlp -O "#EXTINF:%(duration)s,%(upload_date>%d/%m/%Y)s %(title)s" -O webpage_url --playlist-end 10 https://www.youtube.com/user/universetoday > playlist2.m3u

