name: Metrics
on:
  schedule: [{cron: "0 0 1 1 *"}]

  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: nholuongut/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: MattTheTekie
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_sponsors: no
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 24
          plugin_habits: yes
          plugin_habits_from: 400
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_notable: yes
          
  github-contributions-snake:
    runs-on: ubuntu-latest
    needs: github-metrics

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2

      - uses: Platane/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: github-snake.svg?palette=github-dark

      - name: Squash and Commit
        run: |
          git add .
          git reset --soft HEAD~2
          git commit -m "chore: update assets [skip ci]"
          git push -f
