name: Sync Mirrors

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq git curl

      - name: Run sync script
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CODEBERG_USER: ${{ secrets.CODEBERG_USER }}
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}

          # OPTIONAL (only needed for git.gay)
          GITGAY_USER: ${{ secrets.GITGAY_USER }}
          GITGAY_TOKEN: ${{ secrets.GITGAY_TOKEN }}
        run: |
          chmod +x sync_00.sh
          ./sync_00.sh
