name: Encode Secret Example

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Encode TV secret
        shell: bash
        env:
          TV_SECRET: ${{ secrets.JP1 }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$TV_SECRET" | base64
