# Source - https://stackoverflow.com/a/72982005
# Posted by GLM
# Retrieved 2026-04-24, License - CC BY-SA 4.0

- run: 'echo "${{ secrets.TV }}" | base64'
       shell: bash
       env:
         SSH_KEY: ${{ secrets.PRIVATE_KEY }}
